# Generated by Django 4.2.8 on 2023-12-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_options_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_date']},
        ),
        migrations.AddField(
            model_name='comment',
            name='login_require',
            field=models.BooleanField(default=False),
        ),
    ]
