# Generated by Django 4.2.8 on 2023-12-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_options_comment_login_require'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='login_require',
        ),
        migrations.AddField(
            model_name='post',
            name='login_require',
            field=models.BooleanField(default=False),
        ),
    ]
